/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Sat Jan 28 02:28:52 2017. */

#include "multipart_messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t KeypadConfig_ring_buff_cnt_default = 5u;
const uint32_t KeypadConfig_reporting_delay_default = 50000u;
const bool KeypadConfig_KeyConfig_pullup_default = true;
const bool KeypadConfig_KeyConfig_invert_default = true;
const uint32_t KeypadConfig_KeyConfig_debounce_default = 20u;


const pb_field_t KeypadState_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, KeypadState, buttons, buttons, 0),
    PB_LAST_FIELD
};

const pb_field_t KeypadConfig_fields[5] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, KeypadConfig, key_configuration, key_configuration, &KeypadConfig_KeyConfig_fields),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, KeypadConfig, irq_pin, key_configuration, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, KeypadConfig, ring_buff_cnt, irq_pin, &KeypadConfig_ring_buff_cnt_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, KeypadConfig, reporting_delay, ring_buff_cnt, &KeypadConfig_reporting_delay_default),
    PB_LAST_FIELD
};

const pb_field_t KeypadConfig_KeyConfig_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, KeypadConfig_KeyConfig, pin_no, pin_no, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, KeypadConfig_KeyConfig, idx, pin_no, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, KeypadConfig_KeyConfig, pullup, idx, &KeypadConfig_KeyConfig_pullup_default),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, KeypadConfig_KeyConfig, invert, pullup, &KeypadConfig_KeyConfig_invert_default),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, KeypadConfig_KeyConfig, debounce, invert, &KeypadConfig_KeyConfig_debounce_default),
    PB_LAST_FIELD
};

const pb_field_t MultipartMessageConfig_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MultipartMessageConfig, word_size, word_size, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MultipartMessageConfig, word_count, word_size, 0),
    PB_LAST_FIELD
};

const pb_field_t MultipartMessage_fields[4] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, MultipartMessage, keypad_config, keypad_config, &KeypadConfig_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, MultipartMessage, multipart_message_config, keypad_config, &MultipartMessageConfig_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, MultipartMessage, keypad_state, multipart_message_config, &KeypadState_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MultipartMessage, keypad_config) < 65536 && pb_membersize(MultipartMessage, multipart_message_config) < 65536 && pb_membersize(MultipartMessage, keypad_state) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_KeypadState_KeypadConfig_KeypadConfig_KeyConfig_MultipartMessageConfig_MultipartMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MultipartMessage, keypad_config) < 256 && pb_membersize(MultipartMessage, multipart_message_config) < 256 && pb_membersize(MultipartMessage, keypad_state) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_KeypadState_KeypadConfig_KeypadConfig_KeyConfig_MultipartMessageConfig_MultipartMessage)
#endif


/* @@protoc_insertion_point(eof) */
